# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16289381c5f9ae79594b3b5ab7c0a5c4b5da6d1236671cb17842cb338a0cc957a9cb2f6249a44937211995f13eba92e13bfa928790596b3e03b4341f466c645

test:
  secret_key_base: 12193e0ffdfaef77f40aaa3121cd3ec6d2c530d41aeb6c8ea0de6cf7a28e5636c74db5432f4b9b5d4e70adf2f3eca5cecb4b003e3b1dee5d2db2709826071e8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
